name: functional-starter
version: 0.1.0.0
github: "mudont/functional_starter"
license: BSD3
author: "mudont"
maintainer: "maverickone@gmail.com"
copyright: "2021 mudont"

extra-source-files:
  - README.md

synopsis: Functional Kitchen Sink
category: Web

description: Please see the README on GitHub at <https://github.com/mudont/functional_starter#README>
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - TemplateHaskell
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - MultiParamTypeClasses
  - GeneralizedNewtypeDeriving
  - TypeOperators
  - TypeFamilies
  - ConstraintKinds

_exe-defs: &exe-defaults
  source-dirs:
    - app
    - src
    - oneOff
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  dependencies:
    - aeson
    - base >= 4.7 && <= 5.0
    - blaze-html
    - bytestring
    - case-insensitive
    - classy-prelude
    - conduit
    - configurator
    - containers
    - data-has
    - dhall
    - exceptions
    - fast-logger
    - ghc-prim
    - http-types
    - jose
    - katip
    - lens
    - mongoDB
    - mtl
    - natural-transformation
    - network
    - optparse-applicative
    - postgresql-simple
    - raw-strings-qq
    - resource-pool
    - selda
    - selda-postgresql
    - selda-sqlite
    - servant
    - servant-auth
    - servant-auth-server
    - servant-server
    - servant-websockets
    - split
    - stm
    - streamly
    - text
    - threads
    - time
    - transformers
    - unordered-containers
    - uuid
    - vector
    - wai
    - wai-cors
    - wai-logger
    - warp
    - websockets

library:
  <<: *exe-defaults
  exposed-modules:
    - Models
    - ServantWiring
    - API
    - Queries
    - Config
    - CmdArgs

executables:
  server:
    <<: *exe-defaults
    main: Main.hs

  schema:
    <<: *exe-defaults
    main: schema.hs

  # oplog:
  #   <<: *exe-defaults
  #   main: oplogtest.hs

  # tictactoe:
  #   <<: *exe-defaults
  #   main: ticTacToe.hs

  mongoEg:
    <<: *exe-defaults
    main: example.hs

  # cond1:
  #   <<: *exe-defaults
  #   main: example.hs
tests:
  functional-starter-test:
    <<: *exe-defaults
    main: Spec.hs
    dependencies:
      - functional-starter
      - hspec
      - hspec-wai
      - hspec-wai-json
