name: functional-starter
version: 0.1.0.0
github: "mudont/functional_starter"
license: BSD3
author: "mudont"
maintainer: "maverickone@gmail.com"
copyright: "2021 mudont"

extra-source-files:
  - README.md

synopsis: Functional Kitchen Sink
category: Web

description: Please see the README on GitHub at <https://github.com/mudont/functional_starter#README>
default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DuplicateRecordFields
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedLabels
  - OverloadedLists
  - OverloadedStrings
  - PackageImports
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  # Use UndecidableInstances selectively. Not sure if it is dangerous,
  # but seems to relax typechecking in a way you don't always want
  # https://www.reddit.com/r/haskell/comments/5zjwym/when_is_undecidableinstances_okay_to_use/
  # - UndecidableInstances

dependencies:
  - aeson
  - aeson-pretty
  - base ==4.*
  - base >= 4.7 && <= 5.0
  - base-compat
  - base64
  - base64-bytestring
  - binary
  - blaze-html
  - blaze-markup
  - bson
  - bytestring
  - case-insensitive
  - cereal
  - classy-prelude
  - conduit
  - configurator
  - containers
  - cprng-aes
  - crypto-random
  - cryptonite
  - data-default
  - data-has
  - dhall
  - directory
  - exceptions
  - fast-logger
  - fastpbkdf2
  - generic-lens
  - ghc-prim
  - hspec
  - hspec-wai
  - hspec-wai-json
  - http-client
  - http-client-tls
  - http-types
  - Interpolation
  - jose
  - jose-jwt
  - katip
  - lens
  - lens-aeson
  - libiserv
  - memory
  - mime-mail
  - mongoDB
  - mtl
  - natural-transformation
  - network
  - oidc-client
  - opaleye
  - optparse-applicative
  - optparse-generic
  - postgresql-simple
  - profunctors
  - product-profunctors
  - protolude
  - random
  - raw-strings-qq
  - relude
  - resource-pool
  - rio
  - scientific
  - selda
  - selda-postgresql
  - selda-sqlite
  - servant
  - servant-auth
  - servant-auth-server
  - servant-blaze
  - servant-client
  - servant-server
  - servant-websockets
  - smtp-mail
  - split
  - stm
  - streamly
  - string-conv
  - string-interpolate
  - text
  - threads
  - time
  - transformers
  - unordered-containers
  - uuid
  - vector
  - wai
  - wai-app-static
  - wai-cors
  - wai-extra
  - wai-logger
  - warp
  - warp >= 3.2
  - websockets
_exe-defs: &exe-defaults
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall

library:
  source-dirs:
    - src
  exposed-modules:
    - API
    - API.AuthApi
    - API.RajniApi
    - API.TennisApi
    - API.WsApi
    - AppM
    - AppMain
    - Client
    - CmdArgs
    - Config
    - Const
    - DB.Opaleye.Database
    - DB.Opaleye.User
    - DB.Selda.CMModels
    - DB.Selda.Queries
    - DB.Models
    - Err
    - Handlers
    - Handlers.AuthHandler
    - Handlers.RajniHandler
    - Handlers.TennisHandler
    - Handlers.WsHandler
    - ServantWiring
    - Types
    - Util.Crypto
    - Util.Email

executables:
  cmhackersd:
    source-dirs: app
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - base >=4.7 && <5
      - functional-starter

  schema:
    source-dirs: app
    main: schema.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - base >=4.7 && <5
      - functional-starter

  client:
    source-dirs: app
    main: clientMain.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - base >=4.7 && <5
      - functional-starter
tests:
  functional-starter-test:
    <<: *exe-defaults
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - functional-starter
      - hspec
      - hspec-wai
      - hspec-wai-json
