name: functional-starter
version: 0.1.0.0
github: "mudont/functional_starter"
license: BSD3
author: "mudont"
maintainer: "maverickone@gmail.com"
copyright: "2021 mudont"

extra-source-files:
  - README.md

synopsis: Functional Kitchen Sink
category: Web

description: Please see the README on GitHub at <https://github.com/mudont/functional_starter#README>
default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DuplicateRecordFields
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedLabels
  - OverloadedLists
  - OverloadedStrings
  - PackageImports
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

dependencies:
  - aeson
  - aeson-pretty
  - base ==4.*
  - base >= 4.7 && <= 5.0
  - base-compat
  - base64
  - base64-bytestring
  - binary
  - blaze-html
  - blaze-markup
  - bson
  - bytestring
  - case-insensitive
  - cereal
  - classy-prelude
  - conduit
  - configurator
  - containers
  - cprng-aes
  - crypto-random
  - cryptonite
  - data-default
  - data-has
  - dhall
  - directory
  - exceptions
  - fast-logger
  - fastpbkdf2
  - generic-lens
  - ghc-prim
  - hspec
  - hspec-wai
  - hspec-wai-json
  - http-client
  - http-client-tls
  - http-types
  - jose
  - jose-jwt
  - katip
  - lens
  - lens-aeson
  - libiserv
  - memory
  - mime-mail
  - mongoDB
  - mtl
  - natural-transformation
  - network
  - oidc-client
  - optparse-applicative
  - optparse-generic
  - postgresql-simple
  - protolude
  - random
  - raw-strings-qq
  - resource-pool
  - rio
  - selda
  - selda-postgresql
  - selda-sqlite
  - servant
  - servant-auth
  - servant-auth-server
  - servant-blaze
  - servant-client
  - servant-server
  - servant-websockets
  - smtp-mail
  - split
  - stm
  - streamly
  - string-conv
  - string-interpolate
  - text
  - threads
  - time
  - transformers
  - unordered-containers
  - uuid
  - vector
  - wai
  - wai-cors
  - wai-extra
  - wai-logger
  - warp
  - warp >= 3.2
  - websockets
_exe-defs: &exe-defaults
  source-dirs:
    - app
    - src
    - oneOff
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall

library:
  <<: *exe-defaults
  exposed-modules:
    - ServantWiring
    - API
    - Config
    - CmdArgs

executables:
  server:
    <<: *exe-defaults
    main: Main.hs

  schema:
    <<: *exe-defaults
    main: schema.hs

  # oplog:
  #   <<: *exe-defaults
  #   main: oplogtest.hs
  # tictactoe:
  #   <<: *exe-defaults
  #   main: ticTacToe.hs
  # mongoEg:
  #   <<: *exe-defaults
  #   main: example.hs
  # cond1:
  #   <<: *exe-defaults
  #   main: example.hs
tests:
  functional-starter-test:
    <<: *exe-defaults
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - functional-starter
      - hspec
      - hspec-wai
      - hspec-wai-json
